### ISSUE TITLE
Error after Update to Jellyfin 10.9.5

### ISSUE THREAD

**Issue by V1con** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#87]
After the Update to 10.9.5 the plugin isn't able to fetch metadata.

The Logs show this:
ERR] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ThePornDB Scenes"
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at ThePornDB.Providers.Base.GetMetadata(MovieInfo info, SceneType sceneType, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ThePornDB.Providers.Scenes.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by DirtyRacer1337** [comment]
use dev build
